export default {
  mobileShop: "Mobile shop",
  home: "Home",
  about: "About",
  author: "Author",
  signUp: "Sign up",
  signIn: "Sign in",
  login: "Login",
  logout: "Logout",
  emailAddress: "Email Address",
  password: "Password",
  confirmPassword: "Confirm Password",
  register: "Register",
  seeMore: "See more",
  view: "View",
  viewCode: "View Code",
  viewCV: "View CV",
  viewProduct: "View Product",
  createNewAcc: "Create new account",
  haveAnAccount: "Don't have an account?",
  haveAnAcc: "Have an account?",
  landingHomeText1: "Buy phone!",
  landingHomeText2:
    "We got the newest smartphones from Apple, Samsung, LG, Huawei and more.",
  landingHomeText3: "Free shipping in two business days.",
  aboutText1:
    "This mobile shop is an example of a web application highlighting some of the modern technologies. The web application is based on MERN stack - MongoDB, Express.js, and Node.js for back-end and React.js with Redux for front-end.",
  aboutText2:
    "Web application is contained of login system supported with Passportjs authentication, product list backed with various filters and pagination, cart and checkout screen with Paypal paying option supported with Braintree, user account review/edit screen aswell with orders history and admin options like adding new products, deleting products that are listed and dealing with made orders, internationalization for  English and German, and GoogleMaps. The user interface is responsive and it is mainly dealt with inline CSS and Material UI - React UI framework.",
  authorText1:
    "My name is Dino. I am a self-taught web designer/developer from Bosnia with a master's degree in History Science.",
  authorText2:
    "How did I start to code? As a certain hobby, I had an interest in web development during my studies when I met the basics of HTML and CSS. However, with a more serious approach and systematic learning, I started in mid-2017. Back then, I started to explore more in details, mainly through online platforms like freeCodeCamp, Udacity, and Codeacademy as well as various video tutorials and documentation, with areas like jQuery, Responsive web design, CSS Flexbox, JavaScript and JS Algorithms, Data Structures, Object-Oriented and Functional Programming, JSON APIs, Ajax requests, ReactJS, NodeJS and ExpressJS, MongoDB, Git / Github, Braintree / Paypal integration, etc. On this web application, I started working in mid-April 2019. I'm currently learning Redux.",
  orders: "Orders",
  addProduct: "Add product",
  pageNotFound: "Page not found",
  productNotFound: "Product not found",
  searchPhone: "Search phone",
  price: "Price",
  brand: "Brand",
  color: "Color",
  internalMemory: "Internal Memory",
  displaySize: "Display size",
  displayResolution: "Display resolution",
  camera: "Camera",
  name: "Name",
  image: "Photo Link",
  cpu: "CPU",
  Any: "Any",
  "<$249": "<$249",
  "$250-$499": "$250-$499",
  "$500-$749": "$500-$749",
  "$750>": "$750>",
  Apple: "Apple",
  Samsung: "Samsung",
  Huawei: "Huawei",
  LG: "LG",
  HTC: "HTC",
  "8 GB": "8 GB",
  "16 GB": "16 GB",
  "32 GB": "32 GB",
  "64 GB": "64 GB",
  "128 GB": "128 GB",
  "256 GB": "256 GB",
  "512 GB": "512 GB",
  "1 GB": "1 GB",
  "2 GB": "2 GB",
  "3 GB": "3 GB",
  "4 GB": "4 GB",
  "5 GB": "5 GB",
  "6 GB": "6 GB",
  "540 x 960": "540 x 960",
  "720 x 1480": "720 x 1480",
  "1080 x 1920": "1080 x 1920",
  "1125 x 2436": "1125 x 2436",
  "1440 x 2560": "1440 x 2560",
  "1440 x 2880": "1440 x 2880",
  "1440 x 2960": "1440 x 2960",
  '4.5"': '4.5"',
  '5.1"': '5.1"',
  '5.5"': '5.5"',
  '5.8"': '5.8"',
  '6.0"': '6.0"',
  '6.3"': '6.3"',
  '6.6"': '6.6"',
  White: "White",
  Black: "Black",
  Gray: "Gray",
  Blue: "Blue",
  productFound: "product found",
  sort: "Sort by:",
  clearFilters: "Clear filters",
  addToCartSnack: "Item added to your cart.",
  addToCart: "Add to cart",
  noItemsCartText1: "No items in the cart",
  noItemsCartText2: "You can add items to the cart from the dashboard",
  firstPage: "First page",
  lastPage: "Last page",
  nextPage: "Next page",
  backPage: "Back page",
  backToCatalog: "Back to catalog",
  quantity: "Quantity",
  deleteProduct: "Delete product",
  productDeleteDialog: "Are you sure you want to delete this product?",
  cancel: "Cancel",
  confirm: "Confirm",
  model: "Model",
  username: "Username",
  firstName: "First Name",
  lastName: "Last name",
  phone: "Phone",
  city: "City",
  address: "Address",
  email: "Email",
  zipcode: "Zip code",
  deleteAcc: "Delete Account",
  deleteAccDialog: "Delete Account?",
  editAccInfo: "Edit Account Information",
  goBack: "Go back",
  removeProduct: "Remove product",
  orderTotal: "Order total",
  checkout: "Checkout",
  orderDetails: "Order Details",
  date: "Date",
  noOrderMade: "No order made",
  paymentDetails: "Payment Details",
  transDetails: "Transaction details",
  transId: "Transaktions-ID",
  amount: "Amount",
  currency: "Currency",
  paymentMethod: "Payment method",
  cardType: "Card type",
  expDate: "Expiration date",
  customerLoc: "Customer location",
  last4: "Last 4",
  maskNum: "Masked number",
  payerId: "Payer ID",
  paymentId: "Payment ID",
  authId: "Authorization ID",
  payerEmail: "Payer email",
  payerName: "Payer name",
  payerStatus: "Payer status",
  transFee: "Transaction fee",
  close: "Close",
  AwaitingShip: "Awaiting Shipment",
  Shipped: "Shipped",
  Completed: "Completed",
  Cancelled: "Canceled",
  Declined: "Declined",
  orderItems: "Order items",
  total: "Total",
  checkOutText1: "Step 1: Delivery information",
  checkOutText2: "Step 2: Paying options",
  checkOutText3: "Step 3: Confirm the purchase",
  personalDetails: "Personal Details",
  yourAddress: "Your address",
  choosePayOpt: "Please choose option",
  payOption: "Pay option",
  payOnDelivery: "Pay on delivery",
  payOnWeb: "Pay on web",
  confirmPurchase: "Please confirm purchase",
  madeOrderSnack: "You have made the order",
  transMsg: "Transaction Processing. Please wait!",
  selectRam: "Select RAM",
  selectMemory: "Select Memory",
  selectBrand: "Select Brand",
  selectColor: "Select Color",
  customer: "Customer",
  contact: "Contact"
};
