export default {
  mobileShop: "Handy shop",
  home: "Zuhause",
  about: "Über",
  author: "Autor",
  signUp: "Anmelden",
  signIn: "Einloggen",
  login: "Anmeldung",
  logout: "Ausloggen",
  emailAddress: "E-Mail-Addresse",
  password: "Passwort",
  confirmPassword: "Passwort bestätigen",
  register: "Registrieren",
  seeMore: "Mehr Sehen",
  view: "Aussicht",
  viewCode: "Code Anzeigen",
  viewCV: "CV Anzeigen",
  viewProduct: "Produkt anzeigen",
  createNewAcc: "Neuen Account erstellen",
  dontHaveAnAccount: "Ein Konto haben?",
  haveAnAcc: "Ein Konto haben?",
  landingHomeText1: "Telefon kaufen!",
  landingHomeText2:
    "Wir haben die neuesten Smartphones von Apple, Samsung, LG, Huawei und mehr.",
  landingHomeText3: "Kostenloser Versand in zwei Werktagen.",
  aboutText1:
    "Dieser mobile Shop ist ein Beispiel für eine Webanwendung, in der einige der modernen Technologien vorgestellt werden. Die Webanwendung basiert auf dem MERN-Stack - MongoDB, Express.js und Node.js für das Back-End und React.js mit Redux für das Front-End.",
  aboutText2:
    "Die Webanwendung umfasst ein Anmeldesystem, das mit Passportjs-Authentifizierung unterstützt wird, eine Produktliste mit verschiedenen Filtern und Seitenumbrüchen, einen Warenkorb- und Kassenbildschirm mit Paypal-Bezahloption, der mit Braintree unterstützt wird, einen Bildschirm zum Überprüfen / Bearbeiten des Benutzerkontos sowie Bestellverlaufs- und Administratoroptionen zum Hinzufügen neuer Produkte , Löschen von gelisteten Produkten und Abwicklung von Bestellungen, Internationalisierung für Englisch und Deutsch, und GoogleMaps. Die Benutzeroberfläche ist ansprechend und wird hauptsächlich mit Inline-CSS und dem Material-UI-React-UI-Framework behandelt.",
  authorText1:
    "Ich heiße Dino. Ich bin ein autodidaktischer Webdesigner/Entwickler aus Bosnien mit einem Master-Abschluss in Geschichtswissenschaft.",
  authorText2:
    "Wie habe ich angefangen zu codieren? Als gewisses Hobby interessierte ich mich während meines Studiums für Webentwicklung, als ich die Grundlagen von HTML und CSS lernte. Mit einem ernsthafteren Ansatz und systematischem Lernen habe ich Mitte 2017 begonnen. Damals begann ich mich eingehender mit Online-Plattformen wie freeCodeCamp, Udacity und Codeacademy sowie verschiedenen Video-Tutorials und Dokumentationen zu befassen, unter anderem mit jQuery, Responsive Webdesign, CSS Flexbox, JavaScript und JS-Algorithmen sowie Datenstrukturen , Objektorientierte und funktionale Programmierung, JSON-APIs, Ajax-Anforderungen, ReactJS, NodeJS und ExpressJS, MongoDB, Git / Github, Braintree / Paypal-Integration usw. Bei dieser Webanwendung habe ich Mitte April 2019 angefangen zu arbeiten lernt gerade Redux.",
  orders: "Aufträge",
  addProduct: "Produkt hinzufügen",
  pageNotFound: "Seite nicht gefunden",
  productNotFound: "Produkt nicht gefunden",
  searchPhone: "Telefon suchen",
  name: "Name",
  price: "Preis",
  brand: "Marke",
  color: "Farbe",
  internalMemory: "Interner Speicher",
  displaySize: "Bildschirmgröße",
  displayResolution: "Bildschirmauflösung",
  camera: "Kamera",
  image: "Fotolink",
  cpu: "CPU",
  Any: "Alle",
  "<$249": "<$249",
  "$250-$499": "$250-$499",
  "$500-$749": "$500-$749",
  "$750>": "$750>",

  Apple: "Apple",
  Samsung: "Samsung",
  Huawei: "Huawei",
  LG: "LG",
  HTC: "HTC",
  "8 GB": "8 GB",
  "16 GB": "16 GB",
  "32 GB": "32 GB",
  "64 GB": "64 GB",
  "128 GB": "128 GB",
  "256 GB": "256 GB",
  "512 GB": "512 GB",
  "1 GB": "1 GB",
  "2 GB": "2 GB",
  "3 GB": "3 GB",
  "4 GB": "4 GB",
  "5 GB": "5 GB",
  "6 GB": "6 GB",
  "540 x 960": "540 x 960",
  "720 x 1480": "720 x 1480",
  "1080 x 1920": "1080 x 1920",
  "1125 x 2436": "1125 x 2436",
  "1440 x 2560": "1440 x 2560",
  "1440 x 2880": "1440 x 2880",
  "1440 x 2960": "1440 x 2960",
  '4.5"': '4.5"',
  '5.1"': '5.1"',
  '5.5"': '5.5"',
  '5.8"': '5.8"',
  '6.0"': '6.0"',
  '6.3"': '6.3"',
  '6.6"': '6.6"',
  White: "Weiß",
  Black: "Schwarz",
  Gray: "Grau",
  Blue: "Blau",
  productFound: "Produkte gefunden",
  sort: "Sortiere nach:",
  clearFilters: "Filter löschen",
  addToCartSnack: "Artikel wurde Ihrem Warenkorb hinzugefügt.",
  addToCart: "In den Warenkorb legen",
  noItemsCartText1: "Keine Artikel im Warenkorb",
  noItemsCartText2:
    "Sie können über das Dashboard Artikel zum Warenkorb hinzufügen",
  firstPage: "Erste Seite",
  lastPage: "Letzte Seite",
  nextPage: "Nächste Seite",
  backPage: "Rückseite",
  backToCatalog: "Zurück zum Katalog",
  quantity: "Menge",
  deleteProduct: "Produkt löschen",
  productDeleteDialog: "Möchten Sie dieses Produkt wirklich löschen?",
  cancel: "Stornieren",
  confirm: "Bestätigen",
  model: "Modell",
  username: "Nutzername",
  firstName: "Vorname",
  lastName: "Nachname",
  phone: "Telefon",
  email: "Email",
  city: "Stadt",
  address: "Adresse",
  zipcode: "Postleitzahl",
  deleteAcc: "Konto löschen",
  deleteAccDialog: "Konto löschen?",
  editAccInfo: "Kontoinformationen bearbeiten",
  goBack: "Geh zurück",
  removeProduct: "Produkt entfernen",
  orderTotal: "Auftrag insgesamt",
  checkout: "Auschecken",
  orderDetails: "Bestelldetails",
  date: "Datum",
  noOrderMade: "Keine Bestellung gemacht",
  paymentDetails: "Zahlungsdetails",
  transDetails: "Transaktionsdetails",
  transId: "Transaktions-ID",
  amount: "Betrag",
  currency: "Währung",
  paymentMethod: "Zahlungsmethode",
  cardType: "Speicherkarten-Typ",
  expDate: "Haltbarkeitsdatum",
  customerLoc: "Kundenstandort",
  last4: "Letzte 4",
  maskNum: "Maskierte Nummer",
  payerId: "Zahler ID",
  paymentId: "Zahlungs ID",
  authId: "Autorisierungs-ID",
  payerEmail: "E-Mail des Zahlers",
  payerName: "Name des Zahlers",
  payerStatus: "Zahlerstatus",
  transFee: "Transaktionsgebühr",
  close: "Schließen",
  AwaitingShipment: "Warte auf Lieferung",
  Shipped: "Versand erfolgt",
  Completed: "Abgeschlossen",
  Cancelled: "Abgebrochen",
  Declined: "Abgelehnt",
  orderItems: "Auftragspositionen",
  total: "Gesamt",
  checkOutText1: "Schritt 1: Lieferinformationen",
  checkOutText2: "Schritt 2: Bezahloptionen",
  checkOutText3: "Schritt 3: Bestätigen Sie den Kauf",
  personalDetails: "Persönliche Details",
  yourAddress: "Deine Adresse",
  choosePayOpt: "Bitte wählen Sie eine Option",
  payOption: "Bezahloption",
  payOnDelivery: "Zahlung per Nachnahme",
  payOnWeb: "Bezahlen Sie im Web",
  confirmPurchase: "Bitte bestätigen Sie den Kauf",
  madeOrderSnack: "Sie haben die Bestellung gemacht",
  transMsg: "Transaktionsverarbeitung. Warten Sie mal!",
  selectRam: "Wählen Sie RAM",
  selectMemory: "Wählen Sie Speicher",
  selectBrand: "Marke auswählen",
  selectColor: "Wähle Farbe",
  customer: "Kunde",
  contact: "Kontakt"
};
